import fsp from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { google } from 'googleapis';
import { loadAuth, validateProject } from './engine.mjs';

const MARKER = '// Generated by Google Workspace Backup: trigger plan v1';
export function scriptFunctions(content) {
  return [...new Set((content.files || []).filter(f => f.type === 'SERVER_JS').flatMap(file =>
    [...String(file.source || '').matchAll(/^\s*(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/gm)].map(match => match[1])
  ))].filter(name => !name.endsWith('_') && !name.startsWith('gwb')).sort();
}

export function validateTriggerPlan(input, functions) {
  if (!Array.isArray(input) || !input.length || input.length > 20) throw new Error('Il piano deve contenere da 1 a 20 righe.');
  const seen = new Set(), available = new Set(functions);
  return input.map(row => {
    const handler = String(row.handler || '').trim();
    if (handler.length>128 || !/^[A-Za-z_$][\w$]*$/.test(handler) || !available.has(handler)) throw new Error('Funzione non disponibile: ' + handler);
    if (seen.has(handler)) throw new Error('Funzione ripetuta nel piano: ' + handler);
    seen.add(handler);
    const action = row.action || 'replace';
    if (!['replace', 'delete'].includes(action)) throw new Error('Azione trigger non valida.');
    const kind = row.kind || 'daily';
    const out = { handler, action, kind, timeZone: String(row.timeZone || 'Europe/Rome') };
    try { new Intl.DateTimeFormat('en', { timeZone: out.timeZone }); } catch { throw new Error('Fuso orario non valido.'); }
    if (action === 'delete') return out;
    if (['minutes', 'hours'].includes(kind)) {
      out.interval = Number(row.interval);
      const allowed = kind === 'minutes' ? [1, 5, 10, 15, 30] : [1, 2, 4, 6, 8, 12];
      if (!allowed.includes(out.interval)) throw new Error('Intervallo trigger non valido.');
    } else if (['daily', 'weekly'].includes(kind)) {
      out.hour = Number(row.hour); out.minute = Number(row.minute ?? 0);
      if (!Number.isInteger(out.hour) || out.hour < 0 || out.hour > 23 || !Number.isInteger(out.minute) || out.minute < 0 || out.minute > 59) throw new Error('Orario trigger non valido.');
      if (kind === 'weekly') {
        out.weekDay = String(row.weekDay || 'MONDAY');
        if (!['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'].includes(out.weekDay)) throw new Error('Giorno della settimana non valido.');
      }
    } else throw new Error('Tipo trigger non valido.');
    return out;
  });
}

export function triggerSource(plan, planId) {
  return `${MARKER}
// Modifica solo i trigger CLOCK delle funzioni elencate, per l'account corrente.
// Eseguire gwbApplyTriggerPlan dall'editor Apps Script, non da scripts.run.
var GWB_TRIGGER_PLAN = ${JSON.stringify(plan, null, 2)};
var GWB_TRIGGER_PLAN_ID = ${JSON.stringify(planId)};

function gwbExportTriggers() {
  var props = PropertiesService.getUserProperties();
  var configs = JSON.parse(props.getProperty('GWB_TRIGGER_CONFIGS') || '{}');
  var result = {formatVersion:'1.0',scriptId:ScriptApp.getScriptId(),exportedAt:new Date().toISOString(),triggers:[]};
  ScriptApp.getProjectTriggers().forEach(function(t) {
    var id=String(t.getUniqueId());
    result.triggers.push({id:id,handler:t.getHandlerFunction(),eventType:String(t.getEventType()),source:String(t.getTriggerSource()),sourceId:t.getTriggerSourceId()||'',schedule:configs[id]||null});
  });
  console.log(JSON.stringify(result));
  return result;
}

function gwbApplyTriggerPlan() {
  var lock=LockService.getUserLock();
  if(!lock.tryLock(1000)) throw new Error('Un altro piano trigger è in corso.');
  var props=PropertiesService.getUserProperties();
  try {
    if(props.getProperty('GWB_TRIGGER_LAST_PLAN')===GWB_TRIGGER_PLAN_ID) return gwbExportTriggers();
    var cp=JSON.parse(props.getProperty('GWB_TRIGGER_PENDING')||'null');
    if(cp && cp.planId!==GWB_TRIGGER_PLAN_ID) throw new Error('Esiste un piano interrotto. Ripristina il relativo GWB_Triggers.gs e completalo prima del nuovo piano.');
    if(!cp) {
      var handlers=GWB_TRIGGER_PLAN.map(function(row){return row.handler;});
      var old=ScriptApp.getProjectTriggers().filter(function(t){return t.getEventType()===ScriptApp.EventType.CLOCK && handlers.indexOf(t.getHandlerFunction())>=0;});
      cp={planId:GWB_TRIGGER_PLAN_ID,index:0,active:null,old:old.map(function(t){return {id:String(t.getUniqueId()),handler:t.getHandlerFunction()};}),configs:{}};
      props.setProperty('GWB_TRIGGER_PENDING',JSON.stringify(cp));
    }
    // Una regola per volta: non raddoppia tutti i trigger durante la sostituzione.
    // Se una regola fallisce, le precedenti restano applicate e si riprende qui.
    while(cp.index<GWB_TRIGGER_PLAN.length) {
      var row=GWB_TRIGGER_PLAN[cp.index];
      if(!cp.active) {
        cp.active={newId:null};props.setProperty('GWB_TRIGGER_PENDING',JSON.stringify(cp));
      }
      if(row.action!=='delete') {
        if(!cp.active.newId) {
          var b=ScriptApp.newTrigger(row.handler).timeBased().inTimezone(row.timeZone);
          if(row.kind==='minutes') b=b.everyMinutes(row.interval);
          else if(row.kind==='hours') b=b.everyHours(row.interval);
          else {
            b=b.atHour(row.hour).nearMinute(row.minute);
            b=row.kind==='weekly'?b.everyWeeks(1).onWeekDay(ScriptApp.WeekDay[row.weekDay]):b.everyDays(1);
          }
          var id=String(b.create().getUniqueId());cp.active.newId=id;cp.configs[id]=row;
          props.setProperty('GWB_TRIGGER_PENDING',JSON.stringify(cp));
        } else if(!ScriptApp.getProjectTriggers().some(function(t){return String(t.getUniqueId())===cp.active.newId;})) {
          throw new Error('Un trigger appena creato è stato rimosso esternamente. Ripristinalo prima di riprendere il piano.');
        }
      }
      var ids=cp.old.filter(function(t){return t.handler===row.handler;}).map(function(t){return t.id;});
      ScriptApp.getProjectTriggers().forEach(function(t){if(ids.indexOf(String(t.getUniqueId()))>=0) ScriptApp.deleteTrigger(t);});
      cp.index++;cp.active=null;props.setProperty('GWB_TRIGGER_PENDING',JSON.stringify(cp));
    }
    var configs=JSON.parse(props.getProperty('GWB_TRIGGER_CONFIGS')||'{}');
    cp.old.forEach(function(t){delete configs[t.id];});
    Object.keys(cp.configs).forEach(function(id){configs[id]=cp.configs[id];});
    props.setProperty('GWB_TRIGGER_CONFIGS',JSON.stringify(configs));
    props.setProperty('GWB_TRIGGER_LAST_PLAN',GWB_TRIGGER_PLAN_ID);
    props.deleteProperty('GWB_TRIGGER_PENDING');
    return gwbExportTriggers();
  } finally {lock.releaseLock();}
}
`;
}

export async function readScriptProject({ project, credentialsPath, tokenPath, api }) {
  const clean = validateProject(project);
  if (!clean.scriptId) throw new Error('Il progetto non ha uno Script ID.');
  const scriptApi = api || google.script({ version: 'v1', auth: await loadAuth(credentialsPath, tokenPath) });
  const content = (await scriptApi.projects.getContent({ scriptId: clean.scriptId }, { timeout: 60000 })).data;
  return { content, functions: scriptFunctions(content) };
}

export async function prepareTriggerPlan({ project, rows, credentialsPath, tokenPath, directory, api }) {
  const { content, functions } = await readScriptProject({ project, credentialsPath, tokenPath, api });
  const plan = validateTriggerPlan(rows, functions);
  const protectedSet = new Set((project.protectedFiles || []).map(s => s.toLowerCase()));
  if (protectedSet.has('apps-script/gwb_triggers.gs')) throw new Error('GWB_Triggers.gs è intoccabile.');
  const current = (content.files || []).find(f => f.name.toLowerCase() === 'gwb_triggers');
  if (current && (current.type !== 'SERVER_JS' || !current.source.startsWith(MARKER))) throw new Error('Esiste già un file GWB_Triggers non generato dal programma.');
  for (const file of content.files || []) {
    if (file.name.toLowerCase() !== 'gwb_triggers' && file.type === 'SERVER_JS' && /\bfunction\s+gwb(?:ApplyTriggerPlan|ExportTriggers)\s*\(/.test(file.source)) throw new Error('Le funzioni del gestore trigger sono già definite in un altro file.');
  }
  const desired = structuredClone(content);
  desired.files = desired.files.filter(f => f.name.toLowerCase() !== 'gwb_triggers');
  const manifest = desired.files.find(f => f.type === 'JSON' && f.name.toLowerCase() === 'appsscript');
  if (!manifest) throw new Error('Manifest Apps Script mancante.');
  const configuration = JSON.parse(manifest.source);
  if (Array.isArray(configuration.oauthScopes) && !configuration.oauthScopes.includes('https://www.googleapis.com/auth/script.scriptapp')) {
    if (protectedSet.has('apps-script/appsscript.json')) throw new Error('Il manifest intoccabile non concede script.scriptapp. Abilita quel permesso prima del piano.');
    configuration.oauthScopes.push('https://www.googleapis.com/auth/script.scriptapp');
    manifest.source = JSON.stringify(configuration, null, 2);
  }
  const id = crypto.randomUUID(), source = triggerSource(plan, id);
  desired.files.push({ name: 'GWB_Triggers', type: 'SERVER_JS', source });
  const baselineDirectory = path.join(directory, id, 'baseline'), sourceDirectory = path.join(directory, id, 'desired');
  for (const [target, data] of [[baselineDirectory, content], [sourceDirectory, desired]]) {
    const scripts = path.join(target, 'apps-script');
    await fsp.mkdir(scripts, { recursive: true });
    for (const file of data.files) {
      // API logical names become local files: reject path traversal or ambiguous types.
      if (!/^[\p{L}\p{N}_. -]+$/u.test(file.name) || file.name.includes('..') || /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(file.name)) throw new Error('Nome file Apps Script non valido.');
      const ext = { SERVER_JS: '.gs', HTML: '.html', JSON: '.json' }[file.type];
      if (!ext) throw new Error('Tipo file Apps Script non supportato.');
      await fsp.writeFile(path.join(scripts, file.name + ext), file.source);
    }
    await fsp.writeFile(path.join(scripts, '_content-api.json'), JSON.stringify(data, null, 2));
  }
  return { id, projectId: project.id, scriptId: project.scriptId, plan, source, baselineDirectory, sourceDirectory,
    changedFiles: ['apps-script/GWB_Triggers.gs', ...(manifest.source !== content.files.find(f => f.name === manifest.name).source ? ['apps-script/appsscript.json'] : [])] };
}
