import fs from 'node:fs';
import path from 'node:path';
import { root, pkg, runtime, run, checksum, writeChecksum, walk } from './common.mjs';
if (process.platform !== 'win32') throw new Error('Inno Setup richiede Windows. Usa il workflow Windows build.');
const dist = path.join(root, 'dist');
const manifest = JSON.parse(fs.readFileSync(path.join(dist, 'build-manifest.json'), 'utf8'));
if (manifest.version !== pkg.version || manifest.node !== runtime.version) throw new Error('Build non aggiornata: esegui npm run build.');
const names = new Set(manifest.files.map(file => file.path));
for (const file of walk(dist)) if (file !== 'build-manifest.json' && !names.has(file)) throw new Error(`File inatteso in dist: ${file}`);
for (const file of manifest.files) if (checksum(path.join(dist, file.path)) !== file.sha256) throw new Error(`File build modificato: ${file.path}`);
const candidates = [process.env.ISCC_PATH, path.join(process.env['ProgramFiles(x86)'] || 'C:\\Program Files (x86)', 'Inno Setup 6/ISCC.exe')].filter(Boolean);
const compiler = candidates.find(file => fs.existsSync(file));
if (!compiler) throw new Error(`Installa Inno Setup ${runtime.innoVersion}, oppure imposta ISCC_PATH.`);
const release = path.join(root, 'release');
fs.mkdirSync(release, { recursive: true });
run(compiler, [`/DAppVersion=${pkg.version}`, `/DSourceDir=${dist}`, `/DReleaseDir=${release}`, path.join(root, 'installer/GoogleWorkspaceBackup.iss')]);
const output = path.join(release, `GoogleWorkspaceBackup-Setup-${pkg.version}.exe`);
writeChecksum(output);
console.log(`Installer e SHA-256: ${output}`);
